<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Win Steveker">
<meta name="dcterms.date" content="2025-02-25">

<title>Exploring the Relationship Between Democracy and Human Development</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="analysis_files/libs/quarto-html/quarto.js"></script>
<script src="analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analysis_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analysis_files/libs/bootstrap/bootstrap-8a79a254b8e706d3c925cde0a310d4f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description"><span class="header-section-number">2</span> Data Description</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">3</span> Methods</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis"><span class="header-section-number">4</span> Analysis</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exploring the Relationship Between Democracy and Human Development</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Win Steveker </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 25, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>The relationship between democracy and human development or quality of life is the subject of intense debate. Common sense would make one think that democratic governance leads to improved quality of life, given that democracies are presumed to provide greater political freedom, transparency, and accountability and should be providing a better environment for human development to grow.</p>
<p>However, empirical evidence on this topic shows that there appears to be little to no direct relationship between Quality of Life and Democracy in countries. This seems counter-intuitive. With my analysis, I want to confirm or deny these findings and contribute to the discussion to see how levels of democracy impact human development. For this, I have two datasets that contain the Democracy Index (DI) and Human Development Index (HDI) to analyze and quantify their relationship.</p>
<p>My hypothesis of this analysis is that higher levels of democracy, as measured by DI scores, are expected to correlate with improvements in human development, reflected in rising HDI values. Understanding why this is the case is critical, as it informs both academic debates and policy formulations. If democratic governance does not have the direct impact on human development that is often assumed, policymakers might need to focus on other factors, such as economic policies, effective governance, or targeted social interventions, to ensure improvements in quality of life within societies.</p>
</section>
<section id="data-description" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="data-description"><span class="header-section-number">2</span> Data Description</h2>
<p>My analysis has two primary datasets: one for democratic governance and the other for human development outcomes.</p>
<ul>
<li><strong>The Democracy Index (DI) dataset</strong> is compiled by the Economist Intelligence Unit and is accessible via Our World in Data. It measures the quality of democracy across countries by assessing factors such as electoral processes, political participation, civil liberties, and the functioning of government.<br>
</li>
<li><strong>The Human Development Index (HDI)</strong> is sourced from the United Nations Development Programme (UNDP) and is a statistical composite index of life expectancy, education, and per capita income indicators.</li>
</ul>
<p>The datasets span multiple years (2006-2022 combined), which provides time and regional data on how democracy and human development evolve over time in each country. Both have a simple continuous measure that is ideal for regression analysis.</p>
<p>Prior to analysis, the raw datasets were cleaned and preprocessed. The file <code>clean_data.py</code> outlines the procedures for this, but the main points are:</p>
<ul>
<li><strong>Unification of column names and types</strong>: To simplify analysis and coding tasks later on. The <code>year</code> column became an integer, and column names were standardized.<br>
</li>
<li><strong>Scaling and Transformation</strong>: Specific transformations were applied to standardize the scales of the indices. DI values were multiplied by 10 and HDI values by 100. The continuous nature of the indices allows scaling both without loss of information or proportion to a 0 to 100 scale for visual convenience, although it doesn’t matter for the analysis.<br>
</li>
<li><strong>Data Merging and Cleaning</strong>: After cleaning the individual datasets, the two were merged on the <code>country</code> and <code>year</code> columns. The merged DataFrame was then sorted and filtered by country and year. A check showed that almost no or no data at all had to be dropped on the joined DataFrame, except for the non-overlapping countries and years if one was missing in one of the datasets.</li>
</ul>
<p>The datasets should allow for a comprehensive analysis of the relationship between the given variables.</p>
</section>
<section id="methods" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="methods"><span class="header-section-number">3</span> Methods</h2>
<p>This project is a multi-method analytical approach to quantify the impact of democracy on human development. Methods used are:</p>
<section id="ordinary-least-squares-ols-regression" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="ordinary-least-squares-ols-regression"><span class="header-section-number">3.1</span> 1. Ordinary Least Squares (OLS) Regression</h3>
<p>OLS regression serves as the initial analytical framework for examining the relationship between the Democracy Index (DI) and the Human Development Index (HDI). The analysis implements OLS models to quantify the direct effect DI has on HDI. Key steps in the OLS regression process include:</p>
<ul>
<li><strong>Variable Selection and Transformation</strong>:<br>
Prior to fitting the model, independent and dependent variables are extracted from the data. Logarithmic or z-score transformations are applied as needed to stabilize variance and normalize distributions.<br>
</li>
<li><strong>Model Fitting</strong>:<br>
An intercept term is added to the model, and the OLS model is fitted using the <code>statsmodels</code> library. The model summary includes regression coefficients, R-squared values, and statistical tests for significance.<br>
</li>
<li><strong>Diagnostic Checking</strong>:<br>
I am checking all necessary assumptions for my models and adjusting settings and fittings as needed to make my model robust and statistically meaningful. Each assumption check includes a visual and formal check to evaluate if the model’s assumptions all hold.</li>
</ul>
<p>While the OLS models provide a first overview of the data’s relationship, they cannot include the regional data given by the <code>country</code> column.</p>
</section>
<section id="linear-mixed-effects-regression" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="linear-mixed-effects-regression"><span class="header-section-number">3.2</span> 2. Linear Mixed Effects Regression</h3>
<p>A limitation of traditional OLS regression is that the countries are missing from the analysis. To address this, I used mixed models, which allow for the incorporation of both fixed effects (capturing overall trends) and random effects (capturing country-specific deviations).</p>
<ul>
<li><strong>Model Structure</strong>:<br>
The model has fixed effects for the Democracy Index and year and random effects for the country variable.<br>
</li>
<li><strong>Transformation and Preparation</strong>:<br>
Transformations of the data were applied as needed.<br>
</li>
<li><strong>Diagnostic Evaluation</strong>:<br>
Beyond the standard regression assumptions, mixed models have additional checks specific to random effects. These include:
<ul>
<li>Normality of random effects<br>
</li>
<li>Independence between random effects and residuals<br>
</li>
<li>Homoscedasticity of random effects across groups.<br>
Also here, I have a formal and visual test for each to allow for proper evaluation of whether assumptions hold.<br>
</li>
</ul></li>
<li><strong>Model Interpretation</strong>:<br>
I computed the marginal R² (explaining variance attributed solely to fixed effects) and conditional R² (explaining variance from both fixed and random effects). Also, the log-likelihood serves as a guide with the AIC on how well the model is tuned. As we mainly evaluate statistical significance, the p-values are the most interesting measures for us.</li>
</ul>
</section>
<section id="integration-of-methods" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="integration-of-methods"><span class="header-section-number">3.3</span> 3. Integration of Methods</h3>
<p>One of the strengths of this project is that it checks multiple possible relationships via different models. By applying multiple modeling techniques, the analysis is able to provide more meaning if all statistical models/tests come to the same conclusion or if they come to different significance outcomes it highlights what kind of relationship the variables have. For example, although the OLS model may show a weak or insignificant relationship between DI and HDI, the mixed-effects model can reveal whether country-level variations overshadow any underlying effects.</p>
</section>
</section>
<section id="analysis" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="analysis"><span class="header-section-number">4</span> Analysis</h2>
<ul>
<li>In the following DI will refer to the “democracy index”</li>
<li>and HDI will refer to the “human development index”.</li>
<li>Homoscedasticity is not absolutely necessary as an assumption if we do not want to predict values but only check for statistical significance and as long as the visual test holds well enough (Residuals vs.&nbsp;Predicted), technical violations (Beusch-Pegan Test) can be ignored and the model is still robust. That is why in the following analysis we will often say that homoscedasticity is not violated although the formal Beusch-Pegan Test fails because the visual test is showing no bad enough violations of homoscedasticity</li>
</ul>
<div id="6435b989" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sys.dont_write_bytecode <span class="op">=</span> <span class="va">True</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> analysis.clean_data <span class="im">import</span> (</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    get_joined_di_hdi_df,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    YEAR_COL,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    COUNTRY_COL,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    DI_COL,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    HDI_COL,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> analysis.modeling.linear <span class="im">import</span> do_linear_regression</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> analysis.modeling.mixed <span class="im">import</span> do_mixed_linear_regression</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> analysis.transformation <span class="im">import</span> <span class="op">*</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="ea05ace8" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> get_joined_di_hdi_df()</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.head(<span class="dv">5</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.describe())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  country  year  democracy_index  human_development_index
0     AFG  2006             30.6                     41.0
1     AFG  2008             30.2                     43.1
2     AFG  2010             24.8                     44.9
3     AFG  2011             24.8                     45.7
4     AFG  2012             24.8                     46.7
              year  democracy_index  human_development_index
count  2488.000000      2488.000000              2488.000000
mean   2014.806270        54.820981                70.544011
std       4.647901        21.963354                16.057397
min    2006.000000         3.200000                30.300000
25%    2011.000000        35.175000                56.800000
50%    2015.000000        57.500000                72.900000
75%    2019.000000        72.125000                83.600000
max    2022.000000        99.300000                96.700000</code></pre>
</div>
</div>
<div id="7a134878" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="op">=</span> do_linear_regression(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    df<span class="op">=</span>df,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    independent_cols<span class="op">=</span>[YEAR_COL, DI_COL],</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    dependent_col<span class="op">=</span>HDI_COL,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-4-output-1.png" width="668" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-4-output-2.png" width="668" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Linearity Check: holds=False</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-4-output-4.png" width="665" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-4-output-5.png" width="690" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-4-output-6.png" width="670" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-4-output-7.png" width="679" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-4-output-8.png" width="681" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-4-output-9.png" width="619" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-4-output-10.png" width="619" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Outlier Check: holds=True
All assumptions_hold=False
{'_check_homoscedasticity': False,
 '_check_independence': False,
 '_check_linearity': False,
 '_check_multicollinearity': True,
 '_check_normality_of_residuals': True,
 '_check_outliers': True}
                               OLS Regression Results                              
===================================================================================
Dep. Variable:     human_development_index   R-squared:                       0.411
Model:                                 OLS   Adj. R-squared:                  0.410
Method:                      Least Squares   F-statistic:                     920.5
Date:                     Tue, 25 Feb 2025   Prob (F-statistic):          7.25e-300
Time:                             22:22:55   Log-Likelihood:                -9779.1
No. Observations:                     2488   AIC:                         1.956e+04
Df Residuals:                         2485   BIC:                         1.958e+04
Df Model:                                2                                         
Covariance Type:                       HC3                                         
===================================================================================
                      coef    std err          z      P&gt;|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            -834.7544    108.474     -7.695      0.000   -1047.360    -622.148
year                0.4367      0.054      8.114      0.000       0.331       0.542
democracy_index     0.4622      0.011     42.324      0.000       0.441       0.484
==============================================================================
Omnibus:                       19.980   Durbin-Watson:                   0.145
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               15.527
Skew:                          -0.103   Prob(JB):                     0.000425
Kurtosis:                       2.673   Cond. No.                     8.74e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 8.74e+05. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
<p>We can assume linearity holds here, but homosceadasticity and independence are c</p>
<div id="487e2b7e" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>lag <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>HDI_LAG_COL <span class="op">=</span> HDI_COL <span class="op">+</span> <span class="st">"_lag_"</span> <span class="op">+</span> <span class="bu">str</span>(lag)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>df[HDI_LAG_COL] <span class="op">=</span> df.groupby(COUNTRY_COL)[HDI_COL].shift(lag)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>m2 <span class="op">=</span> do_linear_regression(</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    df<span class="op">=</span>df,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    independent_cols<span class="op">=</span>[DI_COL, HDI_LAG_COL, YEAR_COL],</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    dependent_col<span class="op">=</span>HDI_COL,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-5-output-1.png" width="659" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-5-output-2.png" width="674" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-5-output-3.png" width="659" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Linearity Check: holds=True</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-5-output-5.png" width="665" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-5-output-6.png" width="878" height="638" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-5-output-7.png" width="662" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-5-output-8.png" width="679" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-5-output-9.png" width="673" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-5-output-10.png" width="619" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-5-output-11.png" width="620" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-5-output-12.png" width="619" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Outlier Check: holds=True
All assumptions_hold=False
{'_check_homoscedasticity': False,
 '_check_independence': True,
 '_check_linearity': True,
 '_check_multicollinearity': True,
 '_check_normality_of_residuals': True,
 '_check_outliers': True}
                               OLS Regression Results                              
===================================================================================
Dep. Variable:     human_development_index   R-squared:                       0.998
Model:                                 OLS   Adj. R-squared:                  0.998
Method:                      Least Squares   F-statistic:                 4.688e+05
Date:                     Tue, 25 Feb 2025   Prob (F-statistic):               0.00
Time:                             22:22:59   Log-Likelihood:                -2515.8
No. Observations:                     2322   AIC:                             5040.
Df Residuals:                         2318   BIC:                             5063.
Df Model:                                3                                         
Covariance Type:                       HC3                                         
=================================================================================================
                                    coef    std err          z      P&gt;|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
const                           146.9876      8.391     17.518      0.000     130.542     163.433
democracy_index                   0.0006      0.001      0.611      0.541      -0.001       0.003
human_development_index_lag_1     0.9934      0.001    780.986      0.000       0.991       0.996
year                             -0.0725      0.004    -17.442      0.000      -0.081      -0.064
==============================================================================
Omnibus:                     1061.250   Durbin-Watson:                   1.755
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            73342.927
Skew:                          -1.303   Prob(JB):                         0.00
Kurtosis:                      30.409   Cond. No.                     9.92e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 9.92e+05. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
<p>Adding a lag to fix independence Although homosceadasticity fails with the BP Test, the visual test seems to hold and we can say this assumption holds. The R^2 is very high which is most likely due to overfitting of the model due to the lag column we added. But as we can see the year is significant (p&lt;0.05) which suggests time dependent change in HDI. DI is not significant (p&gt;0.05). But the coefficiant of year is negative which is unexpected as we would assume HDI naturally increases over time. This most likely due to the lag overshadowing year affects. We will explore the data more to make our findings statistically more meaningful and also to check their correctness. Different lags were tried and the best was kept which also be the case in the following analysis. Different lags in the analysis have shown to not change the outcome significantly and neither fix any violated assumptions.</p>
<div id="26a4460e" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>delta <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>HDI_DELTA_COL <span class="op">=</span> HDI_COL <span class="op">+</span> <span class="st">"_delta_"</span> <span class="op">+</span> <span class="bu">str</span>(delta)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>df[HDI_DELTA_COL] <span class="op">=</span> df.groupby(COUNTRY_COL)[HDI_COL].diff(<span class="op">-</span>delta).<span class="bu">round</span>(<span class="dv">2</span>).multiply(<span class="op">-</span><span class="dv">1</span>) <span class="op">/</span> delta</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>m3 <span class="op">=</span> do_linear_regression(</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    df<span class="op">=</span>df,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    independent_cols<span class="op">=</span>[DI_COL],</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    dependent_col<span class="op">=</span>HDI_DELTA_COL,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    col_to_transform<span class="op">=</span>{</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>        HDI_DELTA_COL: <span class="kw">lambda</span> x: log_transform(x, scale<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-6-output-1.png" width="700" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Linearity Check: holds=False</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-6-output-3.png" width="665" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-6-output-4.png" width="690" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-6-output-5.png" width="670" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-6-output-6.png" width="679" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-6-output-7.png" width="681" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-6-output-8.png" width="619" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Outlier Check: holds=True
All assumptions_hold=False
{'_check_homoscedasticity': False,
 '_check_independence': True,
 '_check_linearity': False,
 '_check_multicollinearity': True,
 '_check_normality_of_residuals': True,
 '_check_outliers': True}
                                       OLS Regression Results                                       
====================================================================================================
Dep. Variable:     human_development_index_delta_1_&lt;lambda&gt;   R-squared:                       0.001
Model:                                                  OLS   Adj. R-squared:                  0.001
Method:                                       Least Squares   F-statistic:                     2.600
Date:                                      Tue, 25 Feb 2025   Prob (F-statistic):              0.107
Time:                                              22:23:02   Log-Likelihood:                -2938.7
No. Observations:                                      2322   AIC:                             5881.
Df Residuals:                                          2320   BIC:                             5893.
Df Model:                                                 1                                         
Covariance Type:                                        HC3                                         
===================================================================================
                      coef    std err          z      P&gt;|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.4718      0.062      7.620      0.000       0.350       0.593
democracy_index    -0.0015      0.001     -1.613      0.107      -0.003       0.000
==============================================================================
Omnibus:                     2693.572   Durbin-Watson:                   1.572
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           813450.082
Skew:                          -5.516   Prob(JB):                         0.00
Kurtosis:                      94.028   Cond. No.                         160.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)</code></pre>
</div>
</div>
<p>The Year column violated the linearity assumption and was removed in this test. Linearity otherwise seems to hold. The visual shows that homosceadasticity holds well enough after a mild log transform. DI is statistically insignificant (p &gt; 0.05) and the R2 is extremly low which shows that DI has no statistically significant influence on the rate of change of HDI (here delta 1)</p>
<div id="71a7b4c8" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>delta <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>HDI_DELTA_COL <span class="op">=</span> HDI_COL <span class="op">+</span> <span class="st">"_delta_"</span> <span class="op">+</span> <span class="bu">str</span>(delta)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>df[HDI_DELTA_COL] <span class="op">=</span> df.groupby(COUNTRY_COL)[HDI_COL].diff(<span class="op">-</span>delta).<span class="bu">round</span>(<span class="dv">2</span>).multiply(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>df_avg <span class="op">=</span> df.groupby(COUNTRY_COL)[[DI_COL, HDI_DELTA_COL]].mean().reset_index()</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>m4 <span class="op">=</span> do_linear_regression(</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    df<span class="op">=</span>df_avg,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    independent_cols<span class="op">=</span>[DI_COL],</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    dependent_col<span class="op">=</span>HDI_DELTA_COL,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    col_to_transform<span class="op">=</span>{</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>        HDI_DELTA_COL: inverse_transform</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-7-output-1.png" width="733" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Linearity Check: holds=True</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-7-output-3.png" width="665" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-7-output-4.png" width="690" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-7-output-5.png" width="670" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-7-output-6.png" width="670" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-7-output-7.png" width="681" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-7-output-8.png" width="619" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Outlier Check: holds=True
All assumptions_hold=True
{'_check_homoscedasticity': True,
 '_check_independence': True,
 '_check_linearity': True,
 '_check_multicollinearity': True,
 '_check_normality_of_residuals': True,
 '_check_outliers': True}
                                            OLS Regression Results                                           
=============================================================================================================
Dep. Variable:     human_development_index_delta_1_inverse_transform   R-squared:                       0.008
Model:                                                           OLS   Adj. R-squared:                  0.002
Method:                                                Least Squares   F-statistic:                     1.384
Date:                                               Tue, 25 Feb 2025   Prob (F-statistic):              0.241
Time:                                                       22:23:05   Log-Likelihood:                -473.40
No. Observations:                                                166   AIC:                             950.8
Df Residuals:                                                    164   BIC:                             957.0
Df Model:                                                          1                                         
Covariance Type:                                                 HC3                                         
===================================================================================
                      coef    std err          z      P&gt;|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               1.7999      1.062      1.695      0.090      -0.282       3.881
democracy_index     0.0174      0.015      1.176      0.239      -0.012       0.046
==============================================================================
Omnibus:                      263.488   Durbin-Watson:                   1.970
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            39017.301
Skew:                           6.936   Prob(JB):                         0.00
Kurtosis:                      76.815   Cond. No.                         161.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)</code></pre>
</div>
</div>
<p>All assumptions hold here, which is a simplifoed check of the previous statistical test. Also this model shows that the avg DI has no statistical significance (p &gt; 0.05) on the avg rate of change of HDI. Also the R2 shows that the model explains almost none of the variance in the rate of change in HDI.</p>
<div id="e2e875fe" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lag <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>HDI_LAG_COL <span class="op">=</span> HDI_COL <span class="op">+</span> <span class="st">"_lag_"</span> <span class="op">+</span> <span class="bu">str</span>(lag)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>df[HDI_LAG_COL] <span class="op">=</span> df.groupby(COUNTRY_COL)[HDI_COL].shift(lag)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>m5 <span class="op">=</span> do_mixed_linear_regression(</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    df<span class="op">=</span>df,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    independent_cols<span class="op">=</span>[DI_COL, YEAR_COL, HDI_LAG_COL],</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    dependent_col<span class="op">=</span>HDI_COL,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    group_col<span class="op">=</span>COUNTRY_COL,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    random_slope_cols<span class="op">=</span><span class="va">None</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    col_to_transform<span class="op">=</span>{},</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-1.png" width="659" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-2.png" width="659" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-3.png" width="674" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-4.png" width="665" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-5.png" width="690" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-6.png" width="662" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-7.png" width="679" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-8.png" width="673" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-9.png" width="619" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-10.png" width="619" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-11.png" width="620" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-12.png" width="680" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-13.png" width="695" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-14.png" width="713" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-8-output-15.png" width="665" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>All assumptions hold: False
{'_check_homoscedasticity': False,
 '_check_homoscedasticity_of_random_effects': True,
 '_check_independence': True,
 '_check_independence_of_random_effects_and_residuals': True,
 '_check_linearity': 'Evaluate linearity assumption in plots',
 '_check_multicollinearity': True,
 '_check_normality_of_random_effects': True,
 '_check_normality_of_residuals': True,
 '_check_outliers': True}
Marginal R²: 0.998
Conditional R²: 0.9981
model.aic=nan
                   Mixed Linear Model Regression Results
============================================================================
Model:               MixedLM   Dependent Variable:   human_development_index
No. Observations:    2322      Method:               REML                   
No. Groups:          166       Scale:                0.4849                 
Min. group size:     12        Log-Likelihood:       -2521.3836             
Max. group size:     14        Converged:            Yes                    
Mean group size:     14.0                                                   
----------------------------------------------------------------------------
                               Coef.  Std.Err.    z    P&gt;|z|  [0.025  0.975]
----------------------------------------------------------------------------
Intercept                     145.126    7.195  20.171 0.000 131.025 159.228
democracy_index                 0.002    0.001   1.499 0.134  -0.001   0.004
year                           -0.072    0.004 -20.001 0.000  -0.079  -0.065
human_development_index_lag_1   0.991    0.002 600.832 0.000   0.988   0.995
Group Var                       0.028    0.011                              
============================================================================
</code></pre>
</div>
</div>
<p>The lag col was added to fix independence. The visual shows that the homoscedasticity assumption holds. Also this mixed linear regression analysis confirms that DI is statistically insignificant (p &gt; 0.05). However year is significant (p &lt; 0.05) although the negative coefficiant suggests that HDI decreases over time which is historically not the case but is probably caused by the lag overshadowing year positive effects.</p>
<div id="e7598a56" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>delta <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>HDI_DELTA_COL <span class="op">=</span> HDI_COL <span class="op">+</span> <span class="st">"_delta_"</span> <span class="op">+</span> <span class="bu">str</span>(delta)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>df[HDI_DELTA_COL] <span class="op">=</span> df.groupby(COUNTRY_COL)[HDI_COL].diff(<span class="op">-</span>delta).<span class="bu">round</span>(<span class="dv">2</span>).multiply(<span class="op">-</span><span class="dv">1</span>) <span class="op">/</span> delta</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>m5 <span class="op">=</span> do_mixed_linear_regression(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    df<span class="op">=</span>df,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    independent_cols<span class="op">=</span>[DI_COL],</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    dependent_col<span class="op">=</span>HDI_DELTA_COL,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    group_col<span class="op">=</span>COUNTRY_COL,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    col_to_transform<span class="op">=</span>{</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>        DI_COL: z_score_transform,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\winst\anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning:

Maximum Likelihood optimization failed to converge. Check mle_retvals

C:\Users\winst\anaconda3\Lib\site-packages\statsmodels\regression\mixed_linear_model.py:2200: ConvergenceWarning:

Retrying MixedLM optimization with lbfgs
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-9-output-2.png" width="733" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-9-output-3.png" width="665" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-9-output-4.png" width="662" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-9-output-5.png" width="679" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-9-output-6.png" width="673" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-9-output-7.png" width="632" height="523" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-9-output-8.png" width="680" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-9-output-9.png" width="695" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-9-output-10.png" width="713" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/cell-9-output-11.png" width="665" height="521" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>All assumptions hold: False
{'_check_homoscedasticity': False,
 '_check_homoscedasticity_of_random_effects': True,
 '_check_independence': True,
 '_check_independence_of_random_effects_and_residuals': True,
 '_check_linearity': 'Evaluate linearity assumption in plots',
 '_check_multicollinearity': True,
 '_check_normality_of_random_effects': True,
 '_check_normality_of_residuals': True,
 '_check_outliers': True}
Marginal R²: 0.0195
Conditional R²: 0.0644
model.aic=nan
                    Mixed Linear Model Regression Results
=============================================================================
Model:            MixedLM Dependent Variable: human_development_index_delta_1
No. Observations: 2322    Method:             REML                           
No. Groups:       166     Scale:              0.5918                         
Min. group size:  12      Log-Likelihood:     -2733.2570                     
Max. group size:  14      Converged:          Yes                            
Mean group size:  14.0                                                       
-----------------------------------------------------------------------------
                                   Coef.  Std.Err.   z    P&gt;|z| [0.025 0.975]
-----------------------------------------------------------------------------
Intercept                           0.432    0.021 20.928 0.000  0.391  0.472
democracy_index_z_score_transform  -0.045    0.021 -2.177 0.029 -0.085 -0.004
Group Var                           0.028    0.012                           
=============================================================================
</code></pre>
</div>
</div>
<p>z-transform was used on DI_COL to fix numerical instability because the model did not converge. The homoscedasticity assumptions seems to hold in the visual well enough. DI now has a statistically significant affect on the rate of change of HDI (p &lt; 0.05). As this model accounts for country effects it is more reliable than the previous OLS regressions. The analysis is robust with a 2322 observations across 166 groups (countries) and an average group size of 14. However the conditional and marginal R^2 for this model are very low (0.02, 0.06) and suggest that although the effect is statistically significant it explains almost none of the variance within the rate of change of HDI.</p>
<p>The analysis suggests that DI has almost no if any at all influence on the HDI of countries, which is counter-intuitive on first thought but in line with findings of other studies I found.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>